# Generated by Django 6.0.7 on 2026-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("suspend", "Suspended")],
                default="active",
                max_length=10,
            ),
        ),
    ]
