# Generated by Django 6.0.7 on 2026-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("instructor", "Instructor")],
                default="student",
                max_length=20,
            ),
        ),
    ]
