# Generated by Django 6.0.7 on 2026-07-30 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("all", "All Levels"),
                ],
                default="beginner",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="price_must_be_non_negative"
            ),
        ),
    ]
