# Generated by Django 6.0.7 on 2026-07-30 06:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim("name")
                        ),
                        name="unique_lower_trimmed_topic_name",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="topics",
            field=models.ManyToManyField(related_name="courses", to="courses.topic"),
        ),
    ]
