# Generated by Django 6.0.7 on 2026-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_category_slug_topic_course_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="badge",
            field=models.CharField(
                choices=[
                    ("bestseller", "Bestseller"),
                    ("hot", "Hot"),
                    ("new", "New"),
                    ("none", "None"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
