# Generated by Django 6.0.7 on 2026-08-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_section_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order"]},
        ),
    ]
